// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQu1qxME5cDsYQ7GIzMU4MjMeYH9avzP8',
    appId: '1:603124696747:web:2d5c536deb5ec064d719ee',
    messagingSenderId: '603124696747',
    projectId: 'ezi-teach-ams',
    authDomain: 'ezi-teach-ams.firebaseapp.com',
    storageBucket: 'ezi-teach-ams.appspot.com',
    measurementId: 'G-WZQPL216LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYxntPJTcvLkx_gXrh3gYpR5N74Jll9vw',
    appId: '1:603124696747:android:1866d2666ffbfb4fd719ee',
    messagingSenderId: '603124696747',
    projectId: 'ezi-teach-ams',
    storageBucket: 'ezi-teach-ams.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-jxAte-Eo1Wab6XnXb4eKiDAychK6lI',
    appId: '1:603124696747:ios:9faf85ee8c208526d719ee',
    messagingSenderId: '603124696747',
    projectId: 'ezi-teach-ams',
    storageBucket: 'ezi-teach-ams.appspot.com',
    iosBundleId: 'com.eziteach.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu-jxAte-Eo1Wab6XnXb4eKiDAychK6lI',
    appId: '1:603124696747:ios:9faf85ee8c208526d719ee',
    messagingSenderId: '603124696747',
    projectId: 'ezi-teach-ams',
    storageBucket: 'ezi-teach-ams.appspot.com',
    iosBundleId: 'com.eziteach.ams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQu1qxME5cDsYQ7GIzMU4MjMeYH9avzP8',
    appId: '1:603124696747:web:2aacc002b23a9dbcd719ee',
    messagingSenderId: '603124696747',
    projectId: 'ezi-teach-ams',
    authDomain: 'ezi-teach-ams.firebaseapp.com',
    storageBucket: 'ezi-teach-ams.appspot.com',
    measurementId: 'G-5LTWVXDQJ2',
  );
}
